# Generated by Django 4.0.4 on 2022-05-16 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ToDo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('priority', models.CharField(choices=[('CRITICAL', 'critical'), ('IMPORTANT', 'important'), ('NORMAL', 'normal'), ('LOW', 'low')], default='LOW', max_length=10)),
            ],
        ),
    ]
